--HENKEL
SELECT  z.PLANTA
       ,z.ONDA
       ,z.CLIENTE
       ,z.CANAL_CLI
       ,z.PRAZO_CLI
       ,z.PEDIDO
       ,z.SKU
       ,z.DESCRICAO
       ,z.NOMCLI
       ,z.QTD_PEDIDO
       ,z.QTD_ATENDIDA
       ,(z.QTD_ATENDIDA - z.QTD_PEDIDO) AS QTD_CORTE
       ,z.UNI_VENDA
       ,CASE WHEN Z.COD_ERRO = 832 AND Z.TOT_ESTOQUE is null THEN 'RUPTURA TOTAL - SEM ESTOQUE'
             WHEN Z.COD_ERRO = 832 AND Z.TOT_ESTOQUE > 0 AND Z.VLD_DISPO = 0 THEN 'RUPTURA TOTAL - VALIDADE INDISPONIVEL'  WHEN Z.COD_ERRO = 832 AND Z.TOT_ESTOQUE > 0 AND Z.RTB_INDISP > 0 THEN 'RUPTURA TOTAL - PENDENTE ROTULAGEM'
             WHEN Z.COD_ERRO = 832 AND Z.TOT_ESTOQUE > 0 AND Z.IMO_INDISP > 0 THEN 'RUPTURA TOTAL - ESTOQUE IMOBILIZADO'
             WHEN Z.COD_ERRO = 832 AND Z.TOT_ESTOQUE > 0 AND Z.RET_INDISP > 0 THEN 'RUPTURA TOTAL - ESTOQUE RETIDO'  WHEN Z.COD_ERRO = 832 AND Z.TOT_ESTOQUE > 0 AND Z.EST_PUTAWAY > 0 THEN 'RUPTURA TOTAL - PENDENTE ARMAZENAGEM'
             WHEN Z.COD_ERRO = 832 AND Z.TOT_ESTOQUE > 0 AND Z.TOT_ESTOQUE = z.EST_BLOQ THEN 'RUPTURA TOTAL - ESTOQUE BLOQUEADO PARA EXPEDIR'
             WHEN Z.COD_ERRO = 832 THEN 'RUPTURA TOTAL'
             WHEN Z.COD_ERRO = 833 AND Z.TOT_ESTOQUE is null THEN 'RUPTURA TOTAL - SEM ESTOQUE'
             WHEN Z.COD_ERRO = 833 AND Z.TOT_ESTOQUE > 0 AND Z.VLD_DISPO = 0 THEN 'RUPTURA PARCIAL - VALIDADE INDISPONIVEL'  WHEN Z.COD_ERRO = 833 AND Z.TOT_ESTOQUE > 0 AND Z.RTB_INDISP > 0 THEN 'RUPTURA PARCIAL - PENDENTE ROTULAGEM'
             WHEN Z.COD_ERRO = 833 AND Z.TOT_ESTOQUE > 0 AND Z.IMO_INDISP > 0 THEN 'RUPTURA PARCIAL - ESTOQUE IMOBILIZADO'
             WHEN Z.COD_ERRO = 833 AND Z.TOT_ESTOQUE > 0 AND Z.RET_INDISP > 0 THEN 'RUPTURA PARCIAL - ESTOQUE RETIDO'  WHEN Z.COD_ERRO = 833 AND Z.TOT_ESTOQUE > 0 AND Z.EST_PUTAWAY > 0 THEN 'RUPTURA PARCIAL - PENDENTE ARMAZENAGEM'
             WHEN Z.COD_ERRO = 833 AND Z.TOT_ESTOQUE > 0 AND z.EST_BLOQ > 0 THEN 'RUPTURA PARCIAL - ESTOQUE BLOQUEADO PARA EXPEDIR'
             WHEN Z.COD_ERRO = 833 THEN 'RUPTURA PARCIAL' END DESCRICAO_ERRO
       ,z.TOT_ESTOQUE
       ,z.EST_ALOCADO
       ,z.EST_PUTAWAY
       ,z.EST_RPL
       ,z.IMO_INDISP
       ,z.RTB_INDISP
       ,z.RET_INDISP
       ,z.V000
       ,z.V100
       ,z.V365
       ,z.V540
       ,z.VLD_DISPO
       ,z.ENDERECO
FROM
(
	SELECT  A.CODACT PLANTA
	       ,A.NUMVAG ONDA
	       ,A.NOMCLI CLIENTE
	       ,A.CATCLI CANAL_CLI
	       ,E.NBJCTD + 1 PRAZO_CLI
	       ,trim(A.REFLIV) PEDIDO
	       ,trim(A.CODPRO) SKU
	       ,A.DS1PRO DESCRICAO
	       ,a.NOMCLI
	       ,A.UVCCDE QTD_PEDIDO
	       ,A.UVCSRV QTD_ATENDIDA
	       ,A.UNIPRO UNI_VENDA
	       ,A.NUMERR COD_ERRO
	       ,SUM(B.UVCSTO) TOT_ESTOQUE
	       ,SUM(B.UVCDES) EST_ALOCADO
	       ,SUM(case WHEN z.blodes = 1 or r.blodes = 1 THEN B.UVCSTO else 0 end) AS EST_BLOQ
	       ,SUM(CASE WHEN B.ETAPAL = 50 or b.ZONSTS = 'D' THEN B.UVCSTO ELSE 0 END) EST_PUTAWAY
	       ,SUM(CASE WHEN B.ETAPAL = 20 THEN B.UVCSTO ELSE 0 END) EST_RPL
	       ,SUM(CASE WHEN B.MOTIMM IN ('','RTB','RET') THEN 0 ELSE B.UVCSTO END) AS IMO_INDISP
	       ,SUM(CASE WHEN B.MOTIMM = 'RTB' THEN B.UVCSTO ELSE 0 END)             AS RTB_INDISP
	       ,SUM(CASE WHEN B.MOTIMM = 'RET' THEN B.UVCSTO ELSE 0 END)             AS RET_INDISP
	       ,SUM(case when(days(to_date(B.DATFVI || '000000','YYYY-MM-DD hh24:mi:ss')) - days(to_date(C.DATVAG || '000000','YYYY-MM-DD hh24:mi:ss'))) < 0 THEN B.UVCSTO else 0 end) AS V000
	       ,SUM(case when(days(to_date(B.DATFVI || '000000','YYYY-MM-DD hh24:mi:ss')) - days(to_date(C.DATVAG || '000000','YYYY-MM-DD hh24:mi:ss'))) BETWEEN 001 AND 100 THEN B.UVCSTO else 0 end) AS V100
	       ,SUM(case when(days(to_date(B.DATFVI || '000000','YYYY-MM-DD hh24:mi:ss')) - days(to_date(C.DATVAG || '000000','YYYY-MM-DD hh24:mi:ss'))) BETWEEN 101 AND 365 THEN B.UVCSTO else 0 end) AS V365
	       ,SUM(case when(days(to_date(B.DATFVI || '000000','YYYY-MM-DD hh24:mi:ss')) - days(to_date(C.DATVAG || '000000','YYYY-MM-DD hh24:mi:ss'))) BETWEEN 366 AND 540 THEN B.UVCSTO else 0 end) AS V540
	       ,SUM(case when(days(to_date(B.DATFVI || '000000','YYYY-MM-DD hh24:mi:ss')) - days(to_date(C.DATVAG || '000000','YYYY-MM-DD hh24:mi:ss'))) > coalesce(E.NBJCTD,0) THEN B.UVCSTO else 0 end) AS VLD_DISPO
	       ,D.ZONPIC || '-' || LPAD(D.ALLPIC,2,0) || '-' || LPAD(D.DPLPIC,3,0) || '-' || LPAD(D.NIVPIC,2,0) ENDERECO
	FROM FGE50FMSA6.GEERRT A
	LEFT JOIN FGE50FMSA6.GEVAG C
	ON A.NUMVAG = C.NUMVAG
	LEFT JOIN FGE50FMSA6.GEPAL B
	ON A.CODPRO = B.CODPRO
	LEFT JOIN FGE50FMSA6.GEPIC D
	ON A.CODPRO = D.CODPRO
	LEFT JOIN FGE50FMSA6.GECTD E
	ON E.codcli = A.Codcli AND e.typctd = 3
	LEFT JOIN FGE50FMSA6.GEZZON z
	ON z.ZONSTS = b.zonsts
	LEFT JOIN FGE50FMSA6.GEZALL R
	ON r.ZONSTS = b.zonsts AND r.allsts = b.allsts
	WHERE C.ETAVAG = 25
	AND A.CODCLI <> 'ETIQUETA'
	AND A.CODACT = 'HEN'
	GROUP BY  A.CODACT
	         ,A.NUMVAG
	         ,A.REFLIV
	         ,A.CODPRO
	         ,A.DS1PRO
	         ,a.NOMCLI
	         ,A.UVCCDE
	         ,A.UVCSRV
	         ,A.NUMERR
	         ,A.UNIPRO
	         ,D.ZONPIC
	         ,D.ALLPIC
	         ,D.DPLPIC
	         ,D.NIVPIC
	         ,A.CATCLI
	         ,A.NOMCLI
	         ,E.NBJCTD
) z
ORDER BY z.PEDIDO, z.SKU