SELECT  DISTINCT B.CODACT
       ,TO_DATE(A.MAJCRE || right('000000' || A.MAJHMS,6),'yyyymmddhh24miss') DATA_CONTAGEM
       ,A.NUMIVT NUM_INV
       ,A.NUMDOC NUM_DOC
       ,A.NBRCPT CONTAGEM
       ,A.ZONSTS||'-'||A.ALLSTS||'-'||A.DPLSTS||'-'||A.NIVSTS LOCALIZ
       ,B.CODPRO SKU
       ,B.CODPAL PALETE
       ,B.PCBPRO PCB
       ,A.QTECPT+CASE WHEN D.UVCMVT IS NULL THEN 0 ELSE D.UVCMVT END ESTOQUE
       ,A.QTECPT QTD_CONT
       ,D.UVCMVT DESVIO
       ,A.UNICPT UNI
       ,A.MAJUTI USUARIO
FROM FGE50FM0A9.GEIVJSA2 A
LEFT JOIN FGE50FM0A9.GEIVSAI B
ON A.NUMIVT = B.NUMIVT AND A.ZONSTS = B.ZONSTS AND A.ALLSTS = B.ALLSTS AND A.DPLSTS = B.DPLSTS AND A.NIVSTS = B.NIVSTS
LEFT JOIN FGE50FM0A9.GEPAL C
ON B.NUMPAL = C.NUMPAL
LEFT JOIN FGE50FM0A9.GEIVGM D
ON D.NUMIVG = A.NUMIVT AND B.CODPRO = D.CODPRO AND D.NUMPAL = B.NUMPAL
LEFT JOIN FGE50FM0A9.GEIVPAL E
ON A.NUMIVT = E.NUMINV AND A.NUMPAL = E.NUMPAL
WHERE 1 = 1
AND A.NUMIVT = '6077'
ORDER BY TO_DATE(A.MAJCRE || right('000000' || A.MAJHMS, 6), 'yyyymmddhh24miss'), A.NUMIVT, A.NUMDOC, A.NBRCPT, A.ZONSTS||'-'||A.ALLSTS||'-'||A.DPLSTS||'-'||A.NIVSTS 