SELECT  G.CODACT CLIENTE
       ,G.CODPRO SKU
       ,G.DS1PRO SKU_DESCRICAO
       ,SUM(G.UVCSTO) ESTOQUE
       ,COUNT(G.NUMPAL) QTD_LP
       ,ZONSTS ||'-'|| RIGHT('000' || ALLSTS,3) ||'-'|| RIGHT('0000' || DPLSTS,4) ||'-'|| RIGHT('00' || NIVSTS,2) LOCACAO
       ,CASE WHEN P.ZONPIC IS NULL THEN 'LOC'  ELSE 'PIC' END TIPO
       ,G.FAMPRO FAMILIA
       ,TRIM(C.CODCLI) || ' - ' || C.NOMCLI AS PROPRIETARIO
FROM FGE50FM0NS.GEPAL G
LEFT JOIN FGE50FM0NS.GECLI C
ON G.CODACT = C.CODACT AND G.CODCLI = C.CODCLI
LEFT OUTER JOIN FGE50FM0NS.GEPIC p
ON G.CODACT = P.CODACT AND G.CODPRO = P.CODPRO AND ZONPIC ||'-'|| RIGHT('000' || ALLPIC, 3) ||'-'|| RIGHT('0000' || DPLPIC, 4) ||'-'|| RIGHT('00' || NIVPIC, 2) = ZONSTS ||'-'|| RIGHT('000' || ALLSTS, 3) ||'-'|| RIGHT('0000' || DPLSTS, 4) ||'-'|| RIGHT('00' || NIVSTS, 2)
WHERE G.ETAPAL <> '60'
AND G.CODACT = 'HAR'
GROUP BY  G.CODACT
         ,G.CODPRO
         ,G.DS1PRO
         ,ZONSTS ||'-'|| RIGHT('000' || ALLSTS,3) ||'-'|| RIGHT('0000' || DPLSTS,4) ||'-'|| RIGHT('00' || NIVSTS,2)
         ,CASE WHEN P.ZONPIC IS NULL THEN 'LOC'  ELSE 'PIC' END
         ,DS2PRO
         ,FAMPRO
         ,TRIM(C.CODCLI) || ' - ' || C.NOMCLI
         ,CASE WHEN g.MOTIMM = '' AND g.zonsts IN ('A','B','C','D','E','F','G','H','M','S','T') THEN 'DISPONÍVEL'  ELSE 'INDISPONÍVEL' END
ORDER BY  1