SELECT  DISTINCT A.NUMSUP SUPORTE
       ,A.ETASUP STATUS_SUP
       ,A.REFLIV PEDIDO
       ,A.ORISUP SUP_ORIGEM
       ,B.PTYMIS PRIO_MISSAO
       ,CASE WHEN B.ETAMIS = 10 THEN 'A TRATAR'
             WHEN B.ETAMIS = 20 THEN 'AFECTADA'
             WHEN B.ETAMIS = 30 THEN 'TRATADA'
             WHEN B.ETAMIS = 40 THEN 'VALIDADA' END STATUS_MISS
       ,b.NUMMIS MISSAO
FROM FGE50FM0NS.GESUPE A, FGE50FM0NS.GERMIE B, FGE50FM0NS.GESUPD C
WHERE A.NUMSUP = C.NUMSUP
AND C.NUMMIS = B.NUMMIS
AND A.CODACT = 'HAR'
AND a.numsup = '111' 