SELECT  GERECE.CODACT PLANTA
       ,GERECE.CODTRE TIPO
       ,GERECE.REFREC BL
       ,TO_DATE(GERECE.DTRREC|| right('000000'||GERECE.HERREC,6),'YYYY-MM-DD hh24:mi:ss') DT_REC
       ,CASE WHEN GERECE.ETAREC = '0' THEN '(00) - Em processo'
             WHEN GERECE.ETAREC = '10' THEN '(10) - A Receber'
             WHEN GERECE.ETAREC = '20' THEN '(20) - A Receber'
             WHEN GERECE.ETAREC = '30' THEN '(30) - Recebendo'
             WHEN GERECE.ETAREC = '35' THEN '(35) - Durante a ventilação'
             WHEN GERECE.ETAREC = '40' THEN '(40) - Recebido'
             WHEN GERECE.ETAREC = '50' THEN '(50) - Recebido'
             WHEN GERECE.ETAREC = '90' THEN '(90) - # ANULADA'
             WHEN GERECE.ETAREC = '95' THEN '(95) - # ARQUIVADA'  ELSE GERECE.ETAREC END STATUS
       ,GERECE.NOMTRA TRANSP
       ,GERECE.NOMFOU FORNEC
       ,GERECP.CODPRO SKU
       ,GERECP.DS1PRO||' '||GERECP.DS2PRO DESCRICAO_SKU
       ,CASE WHEN GEPRO.ANAPRO is null THEN '# ERRO F4'
             WHEN GEPRO.ANAPRO = '' THEN '# ERRO F4'  ELSE GEPRO.ANAPRO END TIPO
       ,GERECP.CODPAL SSCC
       ,GERECP.MOTIMM STATUS_PLT
       ,GERECP.UVCMVT PECAS
       ,GERECP.UVCMVT * (GEPRO.VOLUVC * 0.001) DM3_UNID
       ,'M3 UNIDADE = ALT:'||GEPRO.HAUUVC||' - COM: '||GEPRO.LNGUVC||' - LAR: '||GEPRO.LRGUVC||' - DM3 Peca: '||GEPRO.VOLUVC M3_UNID
       ,'TIHI PLT: CX: '||GEPRO.COLCOU1||' * CAMADA: '||GEPRO.COUPAL1||' PCS_CX: '||GEPRO.PCBPRO TIHI
FROM FGE50FM0A9.GERECE GERECE
LEFT JOIN FGE50FM0A9.GERECP GERECP
ON GERECE.NUMREC = GERECP.NUMREC AND GERECE.SNUREC = GERECP.SNUREC AND GERECE.CODACT = GERECP.CODACT
LEFT JOIN FGE50FM0A9.GEPRO GEPRO
ON GEPRO.CODACT = GERECP.CODACT AND GEPRO.CODPRO = GERECP.CODPRO
WHERE GERECE.CODACT = 'BRO'
AND GERECP.CODPAL = '1111'
AND GERECE.DTRREC >= 20251117
AND GERECE.DTRREC <= 20251117
ORDER BY GERECE.DTRREC, GERECE.REFREC 