SELECT  CODACT
       ,RIGHT(DATMVT,2)||'/'||SUBSTR(DATMVT,5,2)||'/'||LEFT(DATMVT,4) DATA_MVT
       ,LEFT(HEUMVT,2)||':'||SUBSTR(HEUMVT,2,2)||':'||RIGHT(HEUMVT,2) HORA_MVT
       ,CODUTI MATRICULA
       ,MOTMVT MOTIVO
       ,ZONSTS||'-'||ALLSTS||'-'||DPLSTS||'-'||NIVSTS ENDERECO
       ,CODACT ATIVIDADE
       ,CODPRO SKU
       ,DS1PRO DESCRICAO
       ,PCBPRO PCB
       ,SENMVT||UVCMVT QTD_MVT
       ,CODPAL PALETE
       ,REFMVT REFERENCIA
       ,CASE WHEN CODMDU = 'RG' THEN 'RADIO'  ELSE 'TELA' END TIPO
FROM FGE50FM0NS.GEJNL
WHERE CODPAL = '1111'
AND CODACT = 'HAR'
ORDER BY DATMVT 